/* Declaração de uma lista de objetos //Bianca */
const livros = [
    { codigo: 1, nome: "A divina comédia", autor: "Dante Alighieri", ano: 1472, local: "Itália", resumo: "A divina comédia começa quando Dante tem 35 anos. Depois de viver em pecado, ele decide percorrer o caminho que leva à virtude. Encontra em um lugar inóspito Virgílio, cuja Eneida desperta grande admiração em Dante. O poeta anuncia seu propósito de guiá-lo pelo mundo dos mortos até Deus." },
    { codigo: 2, nome: "Dom Casmurro", autor: "Machado de Assis", ano: 1899, local: "Brasil", resumo: "Bento Santiago se dispõe a narrar a história de sua vida. Trata-se de um homem na casa dos 60 anos, que, supostamente, teria muito o que contar. No entanto, desde logo fica evidente que seu interesse pela própria biografia tem um foco bastante dirigido: o relacionamento com a jovem Capitu, a vizinha que viria a ser o grande amor de sua vida. Personagem fascinante, Capitu possui um extraordinário poder de sedução, manifesto em seus “olhos de cigana oblíqua e dissimulada”, capazes de atrair como a ressaca do mar. " },
    { codigo: 3, nome: "Esaú e Jacó", autor: "Machado de Assis", ano: 1904, local: "Brasil", resumo: "A obra Esaú e Jacó de Machado de Assis, narra a história de Pedro e Paulo, dois irmãos gêmeos que apresentam perfis comportamentais completamente diferentes um do outro, e sua briga pelo amor da mesma mulher, Flora. Os irmãos encarnam a contradição, suas oposições, conflito amoroso e dúvida." },
    { codigo: 4, nome: "A metamorfose", autor: "Franz Kafka", ano: 1915, local: "República Tcheca", resumo: "A Metamorfose é um pequeno livro de autoria do escritor austro-húngaro Franz Kafka. Apesar do texto ter sido feito em 1912 e concluído em apenas 20 dias, ele só foi publicado no ano de 1915. Escrita originalmente em alemão, a novela conta a história do caixeiro-viajante Gregor, que um dia acorda metamorfoseado em um enorme inseto." },
    { codigo: 5, nome: "Eu e outras poesias", autor: "Augusto dos Anjos", ano: 1912, local: "Brasil", resumo: "Eu e outras poesias, conhecido também apenas como Eu é o único livro de poesia de Augusto dos Anjos, publicado no Rio de Janeiro no ano de 1912. A obra se destaca pela visão da vida, numa espécie de réplica à idealização dos temas praticados pelo Parnasianismo." },
    { codigo: 6, nome: "A volta ao mundo em 80 dias", autor: "Julio Verne", ano: 1874, local: "França", resumo: "Phileas Fogg é um senhor inglês, um tanto quanto solitário e sereno, que mora em Londres e tem uma rotina inalterável: acorda sempre no mesmo horário, faz a barba, toma café da manhã e parte para o Reform Club, onde passa o restante do dia. Lá, Fogg almoça e lê os principais jornais da capital inglesa. À noite, reúne-se com os colegas para a tradicional partida de uíste (jogo de cartas para duas duplas, ancestral do Bridge) e para comentar os assuntos do dia. À meia-noite, pontualmente, volta para casa. E assim se segue até o fatídico dia da aposta. Eis que surge um assunto novo: o roubo acontecido no Banco da Inglaterra, dias atrás. O ladrão havia levado 55 mil libras da casa bancária e fugira sem deixar traços. Sentados à mesa, os jogadores especulam a respeito do paradeiro do ladrão. Fogg, até então quieto, comenta que o referido ladrão poderia estar em qualquer lugar, afinal, por causa dos avanços tecnológicos da época, qualquer um seria capaz de dar uma volta ao mundo em apenas 80 dias. Seus colegas dizem que tal façanha seria impossível e que ele não estava levando em conta os imprevistos que a empreitada traria consigo. Fogg permanece firme e, impassível, diz que ele mesmo o faria. Travam então uma aposta de £ 20.000,00 e o destemido cavalheiro decide partir imediatamente. Estaria de volta no dia 21 de Dezembro de 1872." },
    { codigo: 7, nome: "Utopia", autor: "Thomas Morus", ano: 1516, local: "Inglaterra", resumo: "A Utopia é uma obra que pode ser interpretada, sobretudo como uma Crítica Social à Inglaterra das primeiras décadas do século XVI. E não apenas à Inglaterra, mas também a outros estados europeus, como a França, explicitamente citada. Utopia – procura descortinar um pouco das relações políticas que refletem o Pensamento do Contratualismo de Rousseau. Os governantes europeus eram mais interessados na guerra e na expansão de seu próprio poder do que no bem de seus súditos. Há aqui um paralelismo com o argumento de Rafael segundo o qual quanto menos os súditos possuem, tanto melhor para o soberano. Este se sente mais seguro quando aqueles não têm demasiadas riquezas nem gozam de liberdade excessiva." },
    { codigo: 8, nome: "Édipo-Rei", autor: "Sófocles", ano: "século V a.e.c", local: "Grécia", resumo: "O protagonista Édipo é condenado à morte quando ainda era um bebê. O seu pai, o rei Laio, havia ouvido de um oráculo de Delfos que o filho algum dia o mataria e desposaria a própria mãe, a rainha Jocasta. Perturbado com a revelação, o rei julgou que a melhor solução seria matar o menino antes que a profecia se realizasse.Diante da decisão, um pastor é convocado pelo rei para levar Édipo, que teria os pés amarrados e seria deixado pendurado numa árvore no monte Citerão até ser atacado pelas feras. Com pena, o pastor desobedece às ordens e leva o bebê para casa. Por ser muito pobre, a família do camponês não consegue reunir condições de criar Édipo e acaba o doando." },
    { codigo: 9, nome: "Senhora", autor: "José de Alencar", ano: 1875, local: "Brasil", resumo: "A obra Senhora, de José de Alencar é dividida em quatro partes. A primeira delas, nomeada de “O preço do casamento”, começa descrevendo uma jovem moça chamada Aurélia, rica e frequentadora de bailes da alta sociedade. Aurélia, sendo órfã e recebedora de uma grande fortuna, estava sempre acompanhada de sua parenta D. Firmina e acreditava que todos só se interessavam por ela por causa de sua beleza e do seu dinheiro. Em um baile de costume, Aurélia começou a se questionar sobre sua educação e seu destino. Escreveu uma carta ao Sr. Lemos dando-lhe a missão de arrumar seu casamento com o atual noivo de Adelaide Amaral, o Fernando Seixas. Seixas era pertencente a uma família de situação pouco favorável e pretendia arrumar um casamento com uma moça rica para oferecer melhores condições para sua mãe e suas irmãs, e também para seus luxos. Lemos faz a proposta de casamento a Seixas, que mesmo sem conhecer a noiva, recebe um adiantamento do alto dote e aceita o compromisso. Quando foi apresentado à Aurélia, Seixas sente uma profunda humilhação, pois em tempos passados tinha rompido um noivado com ela para ficar noivo de Adelaide, que era mais rica. Na noite de núpcias, Aurélia chama seu então marido de homem vendido." },
    { codigo: 10, nome: "Memórias de um Sargento de Mílicias", autor: "Manuel Antônio de Almeida", ano: 1855, local: "Brasil", resumo: "O livro narra a história de Leonardo, filho de pai do mesmo nome e Maria das Hortaliças. Depois de um escândalo causado pela traição de Maria, o casal toma rumos diferentes.O menino Leonardo, então, viveu criado pelo compadre que o cuidou como se fosse seu filho. Queria que o menino seguisse a vida religiosa mas, depois de passar um tempo na igreja da Sé, o garoto aprontou com o mestre de cerimônia e nunca mais voltou.Durante o tempo em que vive com o compadre, faz visitas à D. Maria, uma senhora rica, que conseguiu a guarda da sobrinha pela qual Leonardo se apaixona.Leonardo Pataca (o pai) se envolve com uma cigana e começa a participar de rituais. Durante um desses rituais o Major Vidigal o prende. A comadre, senhora influente, consegue a liberdade de Leonardo, que se casa com sua filha.Surge então na história José Manuel, que interessado na herança de Luisinha (sobrinha de D. Maria), começa a cortejá-la.Depois que o compadre morre, Leonardo (filho) vai morar com Leonardo Pataca (o pai), porém, não consegue conviver com a madrasta e foge. Vai então morar na casa do antigo amigo de igreja que encontra na rua por acaso. Lá, se apaixona por Vidinha, provocando o ciúme dos outros garotos da casa." },
    { codigo: 11, nome: "As maluquices do Imperador", autor: "Paulo Setúbal", ano: 1927, local: "Brasil", resumo: "O primeiro capítulo começa com a chegada da nau Príncipe Real, trazendo a família real: Maria I , a louca, que vem gritando durante toda a viagem, D. Carlota Joaquina o príncipe regente D. João VI e os Infantes, filhos do príncipe. A partir dai, ao desenrolar dos acontecimentos históricos do nosso país, mergulhamos mais profundamente na intrincada vida pessoal de um dos ocupantes da nau, o futuro D. Pedro I: a bailarina do teatro S. João, Maria Leopoldina de Áustria, o João Pinto, o Chalaça o marquês de Barbacena, entre outros. Todos esses personagens uns mais outros menos conhecidos, realmente existiram e ajudaram a moldar o destino de nosso país. São apresentados ao leitor episódios cômicos e até heróicos, como a resistência ao cerco do Porto, fato que possibilitou a ascendência ao trono de sua filha mais velha, Maria da Glória, ou Maria II de Portugal." },
    { codigo: 12, nome: "A história da guerra do Peloponeso", autor: "Tucídides", ano: "século V a.e.c", local: "Grécia", resumo: "A Guerra do Peloponeso foi um conflito entre as cidades-estados gregas Atenas e Esparta, no século V a.C., pela disputa do domínio da Grécia Antiga. As duas cidades encabeçavam as principais alianças militares da época: a Liga de Delos, liderada por Atenas, e a Liga do Peloponeso, comandada pelos espartanos.A guerra durou aproximadamente 30 anos e foi decisiva para o fim da Era Clássica grega. A guerra foi vencida por Esparta, mas seu domínio sobre a Grécia não durou muito tempo. Os espartanos não conseguiram impedir a invasão dos macedônicos, liderados por Filipe II." },
    { codigo: 13, nome: "O primo Basílio", autor: "Eça de Queirós", ano: 1878, local: "Portugal", resumo: "Segundo grande romance de Eça de Queirós (1845-1900), O primo Basílio é um romance de tese, em que o autor compõe um quadro da vida doméstica burguesa de Lisboa.Luisa, a personagem central da história, é caracterizada pelo temperamento romântico e pela vida fútil e ociosa. Essas características fazem-na uma pessoa frágil, que, na ausência do marido, se enreda nas artimanhas amorosas do primo.Trata-se, portanto, de uma denúncia moral e social do casamento burguês e da educação romântica da mulher, ao mesmo tempo em que é um admirável estudo de tipos e costumes da época" },
    { codigo: 14, nome: "O cortiço", autor: "Aluísio de Azevedo", ano: 1890, local: "Brasil", resumo: "O Cortiço narra a busca do português João Romão pelo enriquecimento e para tal ele explora os empregados e é capaz de tudo para atingir seus objetivos. Romão é dono do cortiço, da taverna e da pedreira. Bertoleza, sua amante, o ajuda trabalhando sem descanso. Opondo-se a João Romão, está Miranda, um comerciante bem sucedido que disputa com o taverneiro um pedaço de terra para aumentar seu quintal, entretanto, não havendo acordo, há o rompimento provisório da relação entre eles." },
    { codigo: 15, nome: "A Falência", autor: "Júlio Lopes de Almeida", ano: 1901, local: "Brasil", resumo: "A falência é o livro mais famoso da escritora Júlia Lopes de Almeida. Conta a história de Camila, uma mulher burguesa, casada com Francisco Teodoro (um rico empresário) e amante do doutor Gervásio. No entanto, com a falência e o posterior suicídio do marido, ela precisa recomeçar.A narrativa está situada na última década do século XIX, no Rio de Janeiro, e mostra os primeiros anos após a Proclamação da República. Assim, com uma linguagem objetiva e antirromântica, apresenta uma visão realista sobre a sociedade da época e, também, traços naturalistas, como o determinismo." },
    { codigo: 16, nome: "Fausto", autor: "Johann Wolfgang von Goethe", ano: 1808, local: "Alemanha", resumo: "A obra-prima de Goethe está dividida em duas partes que são bastante distintas. Na primeira, o autor se baseia na lenda de Fausto e acompanha, sobretudo, a vida amorosa do personagem.Já na segunda, a atenção se volta para as explorações do protagonista pelo desconhecido, refletindo sobre as várias matérias do conhecimento humano que vigoravam na época." },
    { codigo: 17, nome: "Inocência", autor: "Visconde de Taunay", ano: 1872, local: "Brasil", resumo: "O romance passa-se no Sertão de Santana do Paranaíba, onde Martinho dos Santos Pereira (Pereira) vive numa fazenda com sua filha Inocência de 18 anos. De comportamento autoritário, Pereira exige da filha uma obediência que a obrigue ser educada sob seu regime e longe do mundo. Pereira decide que a filha irá se casar com um homem criado no sertão bruto, Manecão, um negociante de gado com índole violenta. Um certo dia, Inocência ficou muito doente e o pai encontrou-se com um rapaz que caminhava pelo sertão e se dizia médico. Era Cirino, que iniciou Farmácia em Ouro Preto e concluiu estudos no colégio do Caraça. Cirino curou Inocência e imediatamente apaixonou-se. Pereira convidou Cirino a ficar em sua casa e lhe arranjou alguns pacientes. Outro hóspede chega trazendo consigo um servo engraçado e uma carta do irmão de Pereira e permanece em sua casa. É o Dr. Meyer, naturalista alemão que embarcou no Brasil com o objetivo de encontrar novas espécies de insetos e caçar borboletas. Embora o anfitrião o tenha recebido normalmente, não compreendeu os elogios que o recém-chegado entregou para sua filha e começou a desconfiar dele." },
    { codigo: 18, nome: "Dom Quixote(v.1)", autor: "Miguel de Cervantes", ano: 1605, local: "Espanha", resumo: "A história relata os feitos de um ingênuo e fidalgo cavaleiro medieval, Dom Quixote. Ao lado dele, estão seu cavalo Rocinante e seu fiel amigo e escudeiro: Sancho Pança.Ávido leitor dos romances de cavalaria, Dom Quixote cria seu próprio mundo ao se lançar em diversas aventuras.Ele vai em busca de justiça e de sua bela donzela imaginária (Dulcineia de Toboso), tal qual ocorriam nas novelas de cavalaria.Ainda que muitas passagens sejam “invenção” de seu protagonista, o romance possui um caráter realista. Vale notar que seu companheiro Sancho apresenta discursos mais coesos e realistas que seu protagonista.O romance relata as histórias e peripécias vividas por Quixote e seu companheiro nas regiões espanholas: La Mancha, Aragão e Catalunha." },
    { codigo: 19, nome: "Iracema", autor: "José de Alencar", ano: 1865, local: "Brasil", resumo: "O romance possui como casal protagonista Iracema e Martim. O primeiro encontro dos dois se dá quando Iracema está repousando em sua sesta quando é assustada por um guerreiro estranho. Assustada, ela lança uma flecha que atinge o guerreiro. Ele não tem nenhuma reação ao ataque de Iracema e, ao ver que ele não possui nenhum tipo de má intenção, parte para acudi-lo. Esse guerreiro chama-se Martim. Eles vão juntos até a tribo de Iracema, chamada de tabajara. Martim é recebido pelo Pajé e, como de costume, belas mulheres são levadas até ele por Iracema. Ele recusa e decide ir embora da tribo. Entretanto, Iracema vai atrás dele, pedindo para ele voltar. Martim aceita. Começa nesse momento uma troca de amor mútuo. À noite, passeiam pelo bosque e ficam muito próximos. Um guerreiro tabajara avista a proximidade dos dois. Ele tenta ferir Iracema e acaba ferindo Martim." },
    { codigo: 20, nome: "A dama das Camélias", autor: "Alexandre Dumas", ano: 1848, local: "França", resumo: "Ler A Dama das Camélias é viajar num tempo em que palavras são paixão, paixão é ação e ação é transformação.O talentoso Alexandre Dumas Filho escreveu com maestria uma estória passional que acabou se tornando um dos maiores romances da dramaturgia de todos os tempos. Um verdadeiro clássico, por assim dizer.Para os mais interessados, vale destacar que o autor reverenciado de A Dama das Camélias veio ao mundo como filho ilegítimo de Alexandre Dumas, o mui famoso responsável pela criação do romance Os Três Mosqueteiros. A Dama das Camélias por sua vez trata-se de uma peça escrita com traços autobiográficos retratando um amor impossível. Marguerite e Armand vivem esse amor impossível.Ela, uma elegante, encantadora e bela cortesã francesa de meados do século XIX, mantida por abastados burgueses. Ele, um homem de família nobre cujo pai, tramando, convence Marguerite que a relação entre ela e Armand é uma destruição para a família e para o futuro do rapaz. Marguerite se deixa enganar e renuncia a Armand, ficando reconhecida como uma cortesã verdadeiramente honesta, humana, responsável pelo resguardo da falsa moral burguesa. Na peça de Dumas, essa cortesã fascinou o mundo!O narrador do romance é o confidente de Armand Duval, que o conhece quando Marguerite já está morta. Esse narrador cede a palavra a diversos outros personagens, que se incumbem de reconstruir o passado dos amantes. A narrativa é composta não linearmente pelos sucessivos relatos de Armand, pela reprodução das cartas escritas pelo casal e pela apresentação do diário dos últimos dias da cortesã, finalizado por sua amiga Julie Duprat.A memorável Dama das Camélias sacrifica-se por seu grande amor, e seu ato de resignação a faz ser reverenciada por todos os homens. Já se diz em todo lugar que: 'o mito central de A Dama das Camélias 'não é o amor, é o reconhecimento: a Dama, Marguerite, ama para ser reconhecida e, a esse título a paixão provém inteiramente de outrem.'" },

]

console.log(livros);

/* *******APLICAÇÃO DO MÉTODO FILTER NO OBJETO********* */

const literaturaEstrangeira = livros.filter(e => e.local !== "Brasil");
console.log(literaturaEstrangeira)

const literaturaNacional = livros.filter(e => e.local == "Brasil");
console.log(literaturaNacional)

const livrosAntigos = livros.filter(e => e.ano < 1900 || e.ano == "século V a.e.c");
console.log(livrosAntigos);

const livrosSec19 = livros.filter(e => e.ano > 1800 && e.ano <= 1900);
console.log(livrosSec19);
/* ****************************** */

//crio uma variável x que irá pegar pelo querySelector todos os buttons que possuem class="botao"
var x = document.querySelectorAll(".botao")
for (let i = 0; i < x.length; i++) {
    //crio um evento com a minha variável que ao clicar no botão irá acionar uma função anonima
    x[i].addEventListener("click", function () {
        //o if irá verificar se o id de determinado botão acionado corresponde ao codigo do array que declaramos acima (linha 1)
        if (Number(x[i].id) === livros[i].codigo) {
            // alert(x[i].id);
            //se a condição do if for verdadeira irá acrescentar no meu id="livro" o nome do livro que foi estabelecido no objeto acima (linha 1)
            document.getElementById("livro").innerText = livros[i].nome;
            document.getElementById("nomeAutor").innerText = livros[i].resumo;
            document.getElementById("Ano").innerText = livros[i].ano;
        }
    });
}
// Tentativa de filtro utilizando o jquery, no futuro pensaremos em algo para solucionar o problema
// $('#linkNacional').click(function () {
//     $('.estrangeiro').hide();
//     $(".nacional").show()
//     // $('.livrosDisponiveis').hide()
//     // $('lNacional').innerHTML += `<h1>Literatura Nacional</h1>`;
// });
// $('#linkEstrangeiro').click(function () {
//     $('.nacional').hide();
//     $(".estrangeiro").show()
// });